server:
  port: 8080

#eureka:
#  client:
#    register-with-eureka: false
#    fetch-registry: false
#    defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
        - id: first-service
          uri: http://localhost:8081
          predicates:
            - Path=/first-service/hello
          filters:
            - SetPath=/hello
            - CustomFilter
        - id: second-service
          uri: http://localhost:8082
          predicates:
            - Path=/second-service/hello
          filters:
            - SetPath=/hello
  redis:
    host: 127.0.0.1
    port: 6379
